---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: centos-7.1
  - name: debian-7.8
  - name: debian-8.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-15.04

suites:
  - name: default
    run_list:
      - recipe[neo4j::default]
  - name: enterprise
    run_list:
      - recipe[neo4j::default]
    attributes:
      neo4j:
        edition: enterprise
  - name: tarball
    run_list:
      - recipe[neo4j::default]
  - name: enterprise-tarball
    run_list:
      - recipe[neo4j::default]
    attributes:
      neo4j:
        edition: enterprise
  - name: latest-default
    run_list:
      - recipe[neo4j::default]
    attributes:
      neo4j:
        release: '2.3.3'
  - name: chef11-default
    run_list:
      - recipe[neo4j::default]
    provisioner:
      require_chef_omnibus: "11.10"
